<?php
// 多语言配置
$langs = [
    'zh-HK' => [
        'home' => '首頁',
        'album' => '相冊',
        'about' => '關於',
        'login' => '登入',
        'team' => 'LKY 攝影隊',
        'school_name' => '聖公會梁季彜中學',
        'school_en' => 'S.K.H. Leung Kwai Yee Secondary School',
        'slogan' => 'ᴄᴀᴘᴛᴜʀɪɴɢ ᴍᴏᴍᴇɴᴛꜱ, ᴄʀᴇᴀᴛɪɴɢ ᴍᴇᴍᴏʀɪᴇꜱ',
        'teacher' => '👨🏼‍🏫 負責老師：梁鑽淇老師',
        'leader1' => '📝 隊長：林靜妍',
        'leader2' => '📝 隊長：陳永添',
        'visit_count' => '總訪問次數',
        'photo_count' => '總照片數目',
        'lang_switch' => 'English',
    'login_title' => '使用 Google 帳號登入',
    'login_btn' => 'Google 登入',
    'login_error' => '僅允許學校帳號或指定電郵登入',
    'welcome_album' => '歡迎 %s 進入相冊頁面！',
    'error_no_code' => '未獲取到授權碼',
    'error_no_token' => '登入失敗，未獲取到 access_token',
    'error_no_email' => '登入失敗，未獲取到電郵',
    'error_invalid_email' => '僅允許學校帳號或指定電郵登入',
    'admin_dashboard' => '管理員後台',
    'access_denied' => '拒絕訪問，您不是管理員',
    'back_home' => '返回首頁'
    ],
    'en' => [
        'home' => 'Home',
        'album' => 'Album',
        'about' => 'About',
        'login' => 'Login',
        'team' => 'Photography Team',
        'school_name' => 'S.K.H. Leung Kwai Yee Secondary School',
        'school_en' => 'S.K.H. Leung Kwai Yee Secondary School',
        'slogan' => 'Capturing Moments, Creating Memories',
        'teacher' => '👨🏼‍🏫 Teacher-in-charge: Mr. Leung Chun Ki',
        'leader1' => '📝 Captain: Lam Ching Yin',
        'leader2' => '📝 Captain: Chan Wing Tim',
        'visit_count' => 'Total Visits',
        'photo_count' => 'Total Photos',
        'lang_switch' => '繁體中文',
    'login_title' => 'Login with Google Account',
    'login_btn' => 'Google Login',
    'login_error' => 'Only school accounts or specified email allowed',
    'welcome_album' => 'Welcome %s to the album page!',
    'error_no_code' => 'Authorization code not received',
    'error_no_token' => 'Login failed, access_token not received',
    'error_no_email' => 'Login failed, email not received',
    'error_invalid_email' => 'Only school accounts or specified email allowed',
    'admin_dashboard' => 'Admin Dashboard',
    'access_denied' => 'Access denied, you are not an admin',
    'back_home' => 'Back to homepage'
    ]
];
